language: node_js

node_js:
- '11'

cache:
  directories: node_modules

before_script:
- npm run build

deploy:
  provider: heroku
  api_key:
    secure: "secure-key"
  app: dezzi-app
  on:
    repo: wellitongervickas/dezzi-app